export const TOGGLE_AUTH = 'TOGGLE_AUTH';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_QUANTITY = 'SET_QUANTITY';
export const SEND_ORDER = 'SEND_ORDER';
export const STORE_ORDER = 'STORE_ORDER';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';